let teamsData=[];let matches=[];let players=[];let odds=[];let marketOdds=null;let gallery=null;let playersMeta={};let selectedTeam='';let squadsByTeam=null;let squadQualityReport=null;let lineupsData=null;let availabilityData=null;
const $=s=>document.querySelector(s);
async function getJson(url,fb){try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(url);return await r.json()}catch(e){return fb}}
function unwrap(payload,key){return payload&&payload.data&&payload.data[key]?payload.data[key]:payload}
function normalizeMatch(m){return Object.assign({},m,{gh:m.gh??m.score_home??'',ga:m.ga??m.score_away??''})}
function flattenSquads(payload){if(!payload||!payload.teams)return null;const out=[];Object.entries(payload.teams).forEach(([team,info])=>(info.players||[]).forEach(p=>out.push(Object.assign({team,group:info.group,squad_status:info.squad_status,source_primary:info.source_primary,fifa_status:info.fifa_status},p))));return out}
async function load(){const ofTeams=await getJson('data/openfootball_teams.json',null);const ofMatches=await getJson('data/openfootball_matches.json',null);teamsData=unwrap(ofTeams,'groups')||await getJson('data/teams.json',[]);const base=(unwrap(ofMatches,'matches')||await getJson('data/matches.json',[])).map(normalizeMatch);squadsByTeam=await getJson('data/squads_by_team.json',null);squadQualityReport=await getJson('data/squad_quality_report.json',null);marketOdds=await getJson('data/market_odds.json',null);gallery=await getJson('data/images.json',null);lineupsData=await getJson('data/lineups.json',{matches:[]});availabilityData=await getJson('data/player_availability.json',{items:[]});const squadPayload=squadsByTeam||await getJson('data/squads_crosscheck.json',null);const playersPayload=squadPayload||await getJson('data/players.json',{players:[]});players=flattenSquads(playersPayload)|| (Array.isArray(playersPayload)?playersPayload:(playersPayload.players||[]));playersMeta=Array.isArray(playersPayload)?{}:playersPayload;odds=await getJson('data/odds.json',[]);const saved=JSON.parse(localStorage.getItem('wc26_matches')||'null');matches=(saved&&saved.length?mergeSaved(base,saved):base);const gf=$('#groupFilter');if(gf)gf.innerHTML='<option value="">Todos los grupos</option>'+teamsData.map(g=>'<option value="'+g.group+'">Grupo '+g.group+'</option>').join('');renderAll()}
function mergeSaved(base,saved){const byId=Object.fromEntries(saved.map(m=>[m.id,m]));return base.map(m=>Object.assign({},m,{gh:byId[m.id]?.gh??m.gh??'',ga:byId[m.id]?.ga??m.ga??'',channel:byId[m.id]?.channel??m.channel}))}
function save(){localStorage.setItem('wc26_matches',JSON.stringify(matches))}
function renderAll(){renderGallery();renderNextHero();renderMatches();renderStandings();renderPlayers();renderThirds();renderBracket()}
function renderGallery(){const b=$('#imageGallery');if(!b)return;const imgs=gallery?.images||[];if(!imgs.length){b.style.display='none';return}b.innerHTML=imgs.slice(0,5).map((x,i)=>'<article class="visual-card '+(i===0?'feature':'')+'"><div class="visual-fallback">'+(['🏟️','🌎','⚽','🙌','🏙️'][i]||'⚽')+'</div><img src="'+x.url+'" alt="'+x.title+'" loading="lazy" onerror="this.style.display=\'none\'"><div><b>'+x.title+'</b><p>'+x.caption+'</p><a href="'+x.source_url+'" target="_blank" rel="noopener">Fuente / licencia</a></div></article>').join('')}
function matchTime(m){const t=(m.time_cl||'00:00').replace(' Chile','');return new Date((m.date||'2026-01-01')+'T'+t+':00-04:00')}
function renderNextHero(){const b=$('#nextMatchHero');if(!b||!matches.length)return;const now=new Date();const upcoming=matches.filter(m=>m.gh===''&&m.ga==='').sort((a,b)=>matchTime(a)-matchTime(b));const m=upcoming.find(x=>matchTime(x)>=now)||upcoming[0]||matches[0];if(!m)return;const mo=marketFor(m);const oddsLine=mo&&mo.outcomes?.length?'<div class="hero-odds">'+mo.outcomes.map(o=>'<span>'+o.name+' <b>'+(o.normalized_probability??'s/d')+'%</b></span>').join('')+'</div>':'';b.innerHTML='<span class="panel-kicker">Próximo partido</span><b>'+m.home+' <em>vs</em> '+m.away+'</b><p>Grupo '+m.group+' · '+m.date+' · '+m.time_cl+' Chile</p><div class="hero-fixture-meta"><span>🏟️ '+(m.venue||'Sede por confirmar')+'</span><span>📺 '+(m.channel||'Por definir')+'</span></div>'+oddsLine}
function updateMatch(id,k,v){matches=matches.map(m=>m.id===id?Object.assign({},m,{[k]:v}):m);save();renderNextHero();renderMatches();renderStandings();renderThirds();renderBracket()}
function marketFor(m){return (marketOdds?.matches||[]).find(x=>x.home_team===m.home&&x.away_team===m.away)}
function oddsHtml(m){const mo=marketFor(m);if(mo&&mo.outcomes?.length){const row=o=>'<div class="odd-row"><span>'+o.name+'</span><div class="bar"><div class="fill" style="width:'+(o.normalized_probability||0)+'%"></div></div><b>'+(o.normalized_probability??'s/d')+'%</b><span class="mini">prom. '+(o.avg_price??'s/d')+' · mejor '+(o.best_price??'s/d')+'</span></div>';return '<div class="odds"><b>📊 Cuotas de mercado</b><div class="mini">'+mo.bookmakers_count+' casas · Actualizado '+(mo.last_update||marketOdds.updated_at||'s/f')+'</div>'+mo.outcomes.map(row).join('')+'<div class="source">Fuente: The Odds API. Cuotas informativas; no constituyen recomendación de apuesta.</div></div>'}return '<div class="odds"><b>📊 Cuotas</b><div class="mini">Sin cuotas o probabilidades cargadas.</div></div>'}
function statusBadge(m){return m.gh!==''&&m.ga!==''?'<span class="chip ok">✅ Resultado ingresado</span>':'<span class="chip">⏳ Programado</span>'}
function renderMatches(){const box=$('#matches');if(!box)return;const q=($('#search')?.value||'').toLowerCase(),g=$('#groupFilter')?.value||'',d=$('#dateFilter')?.value||'';box.innerHTML=matches.filter(m=>(!g||m.group===g)&&(!d||m.date===d)&&[m.group,m.home,m.away,m.channel,m.date,m.venue].join(' ').toLowerCase().includes(q)).map(m=>'<div class="match group-'+m.group+'"><div class="match-top"><span class="group-pill">Grupo '+m.group+'</span><span>'+m.date+' · '+m.time_cl+' Chile</span>'+statusBadge(m)+'<button class="lineup-btn" onclick="openLineupModal(\''+m.id+'\')">📋 Alineaciones</button></div><div class="scoreboard"><div class="side"><span class="team">'+m.home+'</span></div><input value="'+(m.gh||'')+'" oninput="updateMatch(\''+m.id+'\',\'gh\',this.value)" placeholder="0"><div class="vs">VS</div><input value="'+(m.ga||'')+'" oninput="updateMatch(\''+m.id+'\',\'ga\',this.value)" placeholder="0"><div class="side right"><span class="team">'+m.away+'</span></div></div><div class="match-meta"><span class="chip">🏟️ '+(m.venue||'Sede por confirmar')+'</span><span class="chip">📺 <input value="'+(m.channel||'Por definir')+'" oninput="updateMatch(\''+m.id+'\',\'channel\',this.value)"></span></div>'+oddsHtml(m)+'</div>').join('')||'<p class="mini">No hay partidos para mostrar.</p>'}
function lineupFor(id){return (lineupsData?.matches||[]).find(x=>x.match_id===id)||null}
function availabilityFor(team){return (availabilityData?.items||[]).filter(x=>x.team===team)}
function playerList(arr){if(!arr||!arr.length)return '<p class="mini">Sin datos cargados.</p>';return '<ul class="lineup-list">'+arr.map(p=>'<li><b>'+(p.position||'')+'</b> '+(p.name||p.player||p)+'</li>').join('')+'</ul>'}
function teamLineupHtml(label,data,team){const unavailable=[...(data?.unavailable||[]),...availabilityFor(team)];return '<div class="lineup-team"><h3>'+label+'</h3><p class="mini">Formación: '+(data?.formation||'pendiente')+'</p><h4>Titulares</h4>'+playerList(data?.starting)+'<h4>Suplentes</h4>'+playerList(data?.bench)+'<h4>No disponibles / dudas</h4>'+playerList(unavailable.map(x=>({name:x.player||x.name,position:x.status||'',reason:x.reason||''})))+'</div>'}
window.openLineupModal=function(id){const m=matches.find(x=>x.id===id);if(!m)return;const lu=lineupFor(id);const status=lu?.status||'pendiente';const confidence=lu?.confidence||'sin dato';const source=lu?.source_name||lu?.source||'';const sourceUrl=lu?.source_url||'';const body=$('#lineupModalBody');body.innerHTML='<div class="modal-head"><span class="panel-kicker">Alineaciones</span><h2>'+m.home+' vs '+m.away+'</h2><p class="mini">Grupo '+m.group+' · '+m.date+' · '+m.time_cl+' Chile · Estado: <b>'+status+'</b> · Confianza: '+confidence+'</p></div><div class="lineup-status '+status+'">'+(status==='pendiente'?'Alineación oficial pendiente. Normalmente se publica cerca del inicio del partido.':status.toUpperCase())+'</div><div class="lineup-grid">'+teamLineupHtml(m.home,lu?.home,m.home)+teamLineupHtml(m.away,lu?.away,m.away)+'</div><p class="source">Fuente: '+(sourceUrl?'<a href="'+sourceUrl+'" target="_blank" rel="noopener">'+(source||sourceUrl)+'</a>':(source||'sin fuente cargada'))+' · Actualizado: '+(lu?.updated_at||lineupsData?.updated_at||'s/f')+'</p>';$('#lineupModal').classList.add('open');$('#lineupModal').setAttribute('aria-hidden','false')}
window.closeLineupModal=function(){const m=$('#lineupModal');if(m){m.classList.remove('open');m.setAttribute('aria-hidden','true')}}
function calcGroup(group){const gi=teamsData.find(x=>x.group===group);if(!gi)return[];const t={};gi.teams.forEach(n=>t[n]={team:n,group,pj:0,pg:0,pe:0,pp:0,gf:0,gc:0,dg:0,pts:0});matches.filter(m=>m.group===group&&m.gh!==''&&m.ga!=='').forEach(m=>{let h=+m.gh,a=+m.ga;if(isNaN(h)||isNaN(a))return;[m.home,m.away].forEach(n=>{if(!t[n])t[n]={team:n,group,pj:0,pg:0,pe:0,pp:0,gf:0,gc:0,dg:0,pts:0}});t[m.home].pj++;t[m.away].pj++;t[m.home].gf+=h;t[m.home].gc+=a;t[m.away].gf+=a;t[m.away].gc+=h;if(h>a){t[m.home].pg++;t[m.away].pp++;t[m.home].pts+=3}else if(a>h){t[m.away].pg++;t[m.home].pp++;t[m.away].pts+=3}else{t[m.home].pe++;t[m.away].pe++;t[m.home].pts++;t[m.away].pts++}});Object.values(t).forEach(x=>x.dg=x.gf-x.gc);return Object.values(t).sort((a,b)=>b.pts-a.pts||b.dg-a.dg||b.gf-a.gf||a.team.localeCompare(b.team))}
function rows(arr,third=false){return arr.map((r,i)=>{const cls=!third?(i<2?'direct':i===2?'third':'out'):(i<8?'direct':'out');const tag=third?(i<8?'Clasifica':'Fuera'):(i<2?'Clasifica':i===2?'Ranking terceros':'Zona eliminación');return '<tr class="rank-'+cls+'"><td><b>'+(i+1)+'</b></td><td>'+r.team+' <span class="mini">'+(third?'Grupo '+r.group:'')+'</span></td><td><span class="badge '+(cls==='direct'?'ok':'')+'">'+tag+'</span></td><td><b>'+r.pts+'</b></td><td>'+r.pj+'</td><td>'+r.pg+'</td><td>'+r.pe+'</td><td>'+r.pp+'</td><td>'+r.gf+'</td><td>'+r.gc+'</td><td>'+r.dg+'</td></tr>'}).join('')}
function table(body){return '<div class="third-table"><table><thead><tr><th>#</th><th>Equipo</th><th>Estado</th><th>PTS</th><th>PJ</th><th>PG</th><th>PE</th><th>PP</th><th>GF</th><th>GC</th><th>DG</th></tr></thead><tbody>'+body+'</tbody></table></div>'}
function renderStandings(){const b=$('#standings');if(b)b.innerHTML=teamsData.map(g=>'<div class="card group-card group-'+g.group+'"><h3>Grupo '+g.group+'</h3>'+table(rows(calcGroup(g.group)))+'</div>').join('')}
function getThirds(){return teamsData.map(g=>calcGroup(g.group)[2]).filter(Boolean).sort((a,b)=>b.pts-a.pts||b.dg-a.dg||b.gf-a.gf)}
function renderThirds(){const b=$('#thirds');if(b)b.innerHTML=table(rows(getThirds(),true))}
function allTeams(){return teamsData.flatMap(g=>g.teams).sort((a,b)=>a.localeCompare(b))}
function qualityHtml(teams){if(squadQualityReport&&squadQualityReport.summary){const s=squadQualityReport.summary;const weak=(squadQualityReport.teams||[]).filter(r=>r.audit_priority==='alta').map(r=>r.team).slice(0,12);return '<div class="card"><h3>Resumen de calidad</h3><p class="mini"><b>'+s.teams_loaded+'</b> selecciones cargadas · <b>'+s.players_loaded+'</b> jugadores referenciales · <b>'+s.teams_under_10_players+'</b> selecciones con menos de 10 jugadores · <b>'+s.players_with_club_sd+'</b> jugadores con club s/d · <b>'+s.players_with_low_confidence+'</b> con confianza baja · <b>'+s.high_priority_teams+'</b> selecciones prioridad alta.</p><p class="mini">Reporte generado: '+(squadQualityReport.generated_at||'s/f')+'. Prioridad alta: '+(weak.join(', ')||'ninguna')+(weak.length>=12?'…':'')+'</p></div>'}return ''}
function renderPlayers(){const b=$('#players');if(!b)return;if(!players.length){b.innerHTML='<div class="card"><h3>Convocatorias pendientes</h3><p class="mini">'+(playersMeta.note||'Aún no hay jugadores verificados para mostrar.')+'</p></div>';return}const teams=allTeams();if(!selectedTeam)selectedTeam=teams.find(t=>players.some(p=>p.team===t))||teams[0]||'';const teamInfo=squadsByTeam&&squadsByTeam.teams?squadsByTeam.teams[selectedTeam]:null;const teamPlayers=players.filter(p=>p.team===selectedTeam);const warning='<div class="card"><h3>⚠️ Planteles referenciales, no nóminas oficiales FIFA</h3><p class="mini">Estos listados son una base preliminar para seguimiento. Pueden incluir jugadores no convocados, bajas, clubes desactualizados o casos pendientes.</p></div>';const selector='<div class="card"><h3>Planteles por selección</h3><label class="mini">Selecciona país</label><select onchange="selectedTeam=this.value;renderPlayers()">'+teams.map(t=>'<option value="'+t+'" '+(t===selectedTeam?'selected':'')+'>'+t+' ('+players.filter(p=>p.team===t).length+')</option>').join('')+'</select><p class="mini">'+selectedTeam+': '+teamPlayers.length+' jugador(es). Estado: '+(teamInfo?.squad_status||'sin cargar')+' · FIFA: '+(teamInfo?.fifa_status||'pendiente')+'</p></div>';const list=teamPlayers.map(p=>'<div class="player"><b>'+p.name+'</b><span>'+p.position+'</span><span class="badge">'+(p.squad_status||teamInfo?.squad_status||'referencial')+'</span><span class="mini">Club: '+(p.club||'s/d')+' · Fuente base: '+(p.source_primary||teamInfo?.source_primary||'sin fuente')+' · Confianza: '+(p.confidence||'s/d')+'</span></div>').join('')||'<div class="card"><h3>'+selectedTeam+'</h3><p class="mini">Aún no hay jugadores cargados para esta selección.</p></div>';b.innerHTML=warning+qualityHtml(teams)+selector+list}
function renderBracket(){const b=$('#bracket');if(!b)return;const q=[...teamsData.flatMap(g=>calcGroup(g.group).slice(0,2)),...getThirds().slice(0,8)];b.innerHTML='<div class="bracket-note"><b>Clasificados simulados: '+q.length+'/32</b><p class="mini">Cruces exactos pendientes de regla oficial FIFA.</p>'+q.map(x=>'<span class="badge">'+x.team+'</span> ').join('')+'</div>'}
document.addEventListener('click',e=>{if(e.target.classList.contains('tab')){document.querySelectorAll('.tab,.section').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');const t=document.getElementById(e.target.dataset.tab);if(t)t.classList.add('active')}});
window.resetSim=()=>{localStorage.removeItem('wc26_matches');location.reload()};
load();