let teamsData=[];let matches=[];let players=[];
const $=s=>document.querySelector(s);
async function load(){teamsData=await fetch('data/teams.json').then(r=>r.json());const base=await fetch('data/matches.json').then(r=>r.json());players=await fetch('data/players.json').then(r=>r.json());matches=JSON.parse(localStorage.getItem('wc26_matches')||'null')||base;renderAll();}
function save(){localStorage.setItem('wc26_matches',JSON.stringify(matches));}
function renderAll(){renderMatches();renderStandings();renderPlayers();}
function updateMatch(id,key,value){matches=matches.map(m=>m.id===id?{...m,[key]:value}:m);save();renderStandings();}
function renderMatches(){const q=($('#search')?.value||'').toLowerCase();$('#matches').innerHTML=matches.filter(m=>[m.group,m.home,m.away,m.channel,m.date].join(' ').toLowerCase().includes(q)).map(m=>`<div class="match"><div><b>Grupo ${m.group}</b><div class="mini">${m.date} · ${m.time_cl} Chile</div></div><div class="score"><span class="team">${m.home}</span><input value="${m.gh}" oninput="updateMatch('${m.id}','gh',this.value)"><input value="${m.ga}" oninput="updateMatch('${m.id}','ga',this.value)"><span class="team">${m.away}</span></div><div><input value="${m.channel}" oninput="updateMatch('${m.id}','channel',this.value)"></div></div>`).join('');}
function calcGroup(group){const groupInfo=teamsData.find(g=>g.group===group);let table={};groupInfo.teams.forEach(t=>table[t]={team:t,pj:0,pg:0,pe:0,pp:0,gf:0,gc:0,dg:0,pts:0});matches.filter(m=>m.group===group&&m.gh!==''&&m.ga!=='').forEach(m=>{const h=Number(m.gh),a=Number(m.ga);if(Number.isNaN(h)||Number.isNaN(a))return;table[m.home].pj++;table[m.away].pj++;table[m.home].gf+=h;table[m.home].gc+=a;table[m.away].gf+=a;table[m.away].gc+=h;if(h>a){table[m.home].pg++;table[m.away].pp++;table[m.home].pts+=3}else if(a>h){table[m.away].pg++;table[m.home].pp++;table[m.away].pts+=3}else{table[m.home].pe++;table[m.away].pe++;table[m.home].pts++;table[m.away].pts++}});Object.values(table).forEach(t=>t.dg=t.gf-t.gc);return Object.values(table).sort((a,b)=>b.pts-a.pts||b.dg-a.dg||b.gf-a.gf||a.team.localeCompare(b.team));}
function renderStandings(){ $('#standings').innerHTML=teamsData.map(g=>`<div class="card"><h3>Grupo ${g.group}</h3><table><thead><tr><th>Equipo</th><th>PTS</th><th>PJ</th><th>PG</th><th>PE</th><th>PP</th><th>GF</th><th>GC</th><th>DG</th></tr></thead><tbody>${calcGroup(g.group).map((r,i)=>`<tr><td>${i<2?'🏆 ':''}${r.team}</td><td><b>${r.pts}</b></td><td>${r.pj}</td><td>${r.pg}</td><td>${r.pe}</td><td>${r.pp}</td><td>${r.gf}</td><td>${r.gc}</td><td>${r.dg}</td></tr>`).join('')}</tbody></table></div>`).join('');}
function renderPlayers(){ $('#players').innerHTML=players.map(p=>`<div class="player"><b>${p.team}</b><span>${p.name}</span><span class="badge">${p.position}</span><span class="badge">${p.status}</span></div>`).join('');}
document.addEventListener('click',e=>{if(e.target.classList.contains('tab')){document.querySelectorAll('.tab,.section').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');document.getElementById(e.target.dataset.tab).classList.add('active');}});
window.resetSim=()=>{localStorage.removeItem('wc26_matches');location.reload();};
load();
